GlobalPlanner:     

  allow_unknown: true
  default_tolerance: 0.05
  visualize_potential: true
  use_dijkstra: false
  use_quadratic: true
  use_grid_path: true
  old_navfn_behavior: false
  lethal_cost: 253
  neutral_cost: 50
  cost_factor: 3.0
  publish_potential: true
  orientation_mode: 2
  outline_map: false
